Fix eth_sendTransaction and add more RPC methods
cawabunga/headless-web3-provider pull request #12
Opened 2023-09-15 01:32 UTC by dahu33

This PR tries to make `headless-web3-provider` even more awesome:
1) fixed the `eth_sendTransaction` method which was broken when passing the `type` or `gas` parameters (JSON-RPC transaction need to be converted to an ethers.js transaction).
2) added tests for the above
3) added some missing pass-through RPC methods

@cawabunga if you could have a look that would be great! Thanks!

2023-09-16 15:14 UTC, cawabunga requested changes

2023-09-16 15:14 UTC, cawabunga commented on tests/e2e/metamask.spec.ts
> +  await wallet.authorize(Web3RequestKind.SendTransaction)
Let's get `nonceBefore` right before authorizing the request, so we will be sure that transaction is not sent before it.

2023-09-16 15:14 UTC, cawabunga commented on src/Web3ProviderBackend.ts
> +function convertTransaction(tx: { [key: string]: any }): ethers.providers.TransactionRequest {
Even though return type is specified, it is not very clear what the input and the output are. Maybe something like `convertTxObjectToEthersTxRequest`?

2023-09-16 15:14 UTC, cawabunga commented on package.json
> +    "@playwright/test": "^1.38.0",
If there is no real necessity, let's skip upgrading.

2023-09-16 15:14 UTC, cawabunga commented on playwright.config.ts
> +  /* Disable parallelism to avoid the `nonce has already been used` issue */
I fixed that in different way: https://github.com/cawabunga/headless-web3-provider/pull/13

2023-09-19 01:44 UTC, dahu33 commented
@cawabunga thanks for the review, I've addressed your feedback, could you please have another look?

2023-09-19 06:09 UTC, cawabunga approved these changes
> @cawabunga thanks for the review, I've addressed your feedback, could you please have another look?

All good, thanks for the PR! 🙂

2023-09-19 06:09 UTC, merged

2023-09-19 07:11 UTC, cawabunga commented
Published as [0.2.3](https://www.npmjs.com/package/headless-web3-provider/v/0.2.3)